#include <iostream>
#include <string>
#include <algorithm>
#include <vector>
#include <bitset>
#include <stack>
#include <map>
using namespace std;
/************************************************************************/
/*
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 * 
 * 分析
 * 两个字符串s和t，其中t是由s中的所有字符乱序之后+1个字符组成，要求找出t中多的那个字符。
 *
 * 思路
 * 将s和t相连考虑，题目变成一个字符数组，其中只有一个字符只出现了一次，其余字符出现了两次，要求找出只出现了一次的字符。
 * 这通过异或的方法很容易找出。
*/
/************************************************************************/
char findTheDifference(string s, string t) {
	char cRes = s[0];
	for (int i = 1; i < s.length(); i++)
		cRes ^= s[i];
	for (int i = 0; i < t.length(); i++)
		cRes ^= t[i];
	return cRes;
}
int main()
{
	string s = "abcd";
	string t = "abcde";
	char c = findTheDifference(s, t);
	return 0;
}